FROM baseimg

WORKDIR /usr/src/app/packages/ui

RUN yarn build

FROM nginx:1.15.5-alpine

COPY --from=baseimg /usr/src/app/packages/ui/dist /usr/share/nginx/html

COPY --from=baseimg /usr/src/app/packages/ui/nginx.conf /etc/nginx/nginx.conf
COPY --from=baseimg /usr/src/app/packages/ui/nginx-site.conf /etc/nginx/conf.d/default.conf

