version: '3'
services:
  redis:
    image: redis:7.0.5

  frontend:
    image: 127.0.0.1:5000/frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - 8000:80

  backend:
    image: 127.0.0.1:5000/backend
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - 8082:8082
    environment:
      - REDIS_HOSTNAME=redis
      - REDIS_PORT=6379

  socket:
    image: 127.0.0.1:5000/socket
    build:
      context: .
      dockerfile: Dockerfile.socket
    ports:
      - 3052:3052
    environment:
      - REDIS_HOSTNAME=redis
      - REDIS_PORT=6379
