version: '3'
services:
  frontend:
    image: 127.0.0.1:5000/frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - 80:8080

  backend:
    image: 127.0.0.1:5000/backend
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - 8082:8082


  backend:
    image: 127.0.0.1:5000/socket
    build:
      context: .
      dockerfile: Dockerfile.socket
    ports:
      - 3052:3052
